### PR TITLE
`-i/--install-directly` option

### PR DESCRIPTION
**Pull request by rpkak**
implement #25

`-i` and `--install-directly` will install the package directly.

### CODE REVIEW

**Comment by windowz414** [comment]
Just reviewed the changes, and they all seem good. I'll be testing it on my laptop as well by running a full AUR package updates. I hope it will work that way.

What will I run: `sudo ./local-aur build --update-all --install-directly`

**Comment by windowz414** [comment]
I think the case of combining with `--update-all` wasn't overseen. Here's the traceback I have gotten;
```
==> Finished making: heroic-games-launcher-bin 2.4.0-2 (Mon 15 Aug 2022 03:33:06 PM +03)
Traceback (most recent call last):
  File "/home/beru/local-aur/./local-aur", line 254, in <module>
    build_packages(args.packages, args.update_all,
  File "/home/beru/local-aur/./local-aur", line 118, in build_packages
    new_dest_files = build_package(package)
  File "/home/beru/local-aur/./local-aur", line 71, in build_package
    os.rename(quote(file), quote(dest))
OSError: [Errno 18] Invalid cross-device link: '/tmp/heroic-games-launcher-bin.local-aur.8qm92k6e/heroic-games-launcher-bin-2.4.0-2-x86_64.pkg.tar.zst' -> '/var/lib/local-aur/repo/heroic-games-launcher-bin-2.4.0-2-x86_64.pkg.tar.zst'
sudo ./local-aur build --update-all --install-directly  34.19s user 12.32s system 35% cpu 2:10.78 total
```

**Comment by windowz414** [comment]
> I think the case of combining with `--update-all` wasn't overseen. Here's the traceback I have gotten;
> 
> ```
> ==> Finished making: heroic-games-launcher-bin 2.4.0-2 (Mon 15 Aug 2022 03:33:06 PM +03)
> Traceback (most recent call last):
>   File "/home/beru/local-aur/./local-aur", line 254, in <module>
>     build_packages(args.packages, args.update_all,
>   File "/home/beru/local-aur/./local-aur", line 118, in build_packages
>     new_dest_files = build_package(package)
>   File "/home/beru/local-aur/./local-aur", line 71, in build_package
>     os.rename(quote(file), quote(dest))
> OSError: [Errno 18] Invalid cross-device link: '/tmp/heroic-games-launcher-bin.local-aur.8qm92k6e/heroic-games-launcher-bin-2.4.0-2-x86_64.pkg.tar.zst' -> '/var/lib/local-aur/repo/heroic-games-launcher-bin-2.4.0-2-x86_64.pkg.tar.zst'
> sudo ./local-aur build --update-all --install-directly  34.19s user 12.32s system 35% cpu 2:10.78 total
> ```

Update: This error happens when I run the command normally as well: `sudo local-aur build --install-directly uml_utilities`

**Comment by rpkak** [comment]
I think, that the reason that you get an error is, that `/tmp` and `/var` are not on the same filesystem. This function change may have fixed it.

**Comment by windowz414** [comment]
> I think, that the reason that you get an error is, that `/tmp` and `/var` are not on the same filesystem. This function change may have fixed it.

`/var` is inside rootfs while `/tmp` is mounted as tmpfs for my case. After that commit of yours, things seem to be working properly this time. I have successfully rebuilt and installed `uml_utilities` package. Now trying to perform a full upgrade with the first command I tried: `sudo ./local-aur build --update-all --install-directly`

**Comment by windowz414** [comment]
Tests pass, ready to ship!

```
eru@hinodeai ~/local-aur (git)-[install-directly] % sudo ./local-aur build --update-all --install-directly
[snip utd msgs]
Cloning into '/tmp/google-chrome.local-aur.dfh3jim2'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8 (delta 0), reused 6 (delta 0), pack-reused 0
Receiving objects: 100% (8/8), 18.65 KiB | 9.32 MiB/s, done.
==> Making package: google-chrome 104.0.5112.101-1 (Wed 17 Aug 2022 11:08:34 AM +03)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading google-chrome-stable_104.0.5112.101-1_amd64.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 85.7M  100 85.7M    0     0  2859k      0  0:00:30  0:00:30 --:--:-- 2812k
  -> Found eula_text.html
  -> Found google-chrome-stable.sh
==> Validating source files with sha512sums...
    google-chrome-stable_104.0.5112.101-1_amd64.deb ... Passed
    eula_text.html ... Passed
    google-chrome-stable.sh ... Passed
==> Extracting sources...
  -> Extracting google-chrome-stable_104.0.5112.101-1_amd64.deb with bsdtar
==> Entering fakeroot environment...
==> Starting package()...
  -> Extracting the data.tar.xz...
  -> Moving stuff in place...
  -> Fixing Chrome desktop entry...
  -> Removing Debian Cron job, duplicate product logos and menu directory...
==> Tidying install...
  -> Removing empty directories...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "google-chrome"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Adding install file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: google-chrome 104.0.5112.101-1 (Wed 17 Aug 2022 11:09:32 AM +03)
[snip utd msgs]
==> Extracting local-aur.db.tar.gz to a temporary location...
==> Extracting local-aur.files.tar.gz to a temporary location...
==> Adding package '/var/lib/local-aur/repo/google-chrome-104.0.5112.101-1-x86_64.pkg.tar.zst'
  -> Computing checksums...
  -> Removing existing entry 'google-chrome-104.0.5112.79-1'...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file '/var/lib/local-aur/repo/local-aur.db.tar.gz'
:: Synchronizing package databases...
 gnome-unstable is up to date
 testing is up to date
 core is up to date
 extra is up to date
 community-testing is up to date
 community is up to date
 multilib-testing is up to date
 multilib is up to date
 local-aur                                                                13.3 KiB  66.5 KiB/s 00:00 [------------------------------------------------------------] 100%
resolving dependencies...
looking for conflicting packages...

Package (1)              Old Version      New Version       Net Change  Download Size

local-aur/google-chrome  104.0.5112.79-1  104.0.5112.101-1    0.51 MiB     116.87 MiB

Total Download Size:   116.87 MiB
Total Installed Size:  280.08 MiB
Net Upgrade Size:        0.51 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 google-chrome-104.0.5112.101-1-x86_64                                   116.9 MiB   295 MiB/s 00:00 [------------------------------------------------------------] 100%
(1/1) checking keys in keyring                                                                       [------------------------------------------------------------] 100%
(1/1) checking package integrity                                                                     [------------------------------------------------------------] 100%
(1/1) loading package files                                                                          [------------------------------------------------------------] 100%
(1/1) checking for file conflicts                                                                    [------------------------------------------------------------] 100%
(1/1) checking available disk space                                                                  [------------------------------------------------------------] 100%
:: Processing package changes...
(1/1) upgrading google-chrome                                                                        [------------------------------------------------------------] 100%
==> NOTE: Custom flags should be put directly in: ~/.config/chrome-flags.conf
==> NOTE: The launcher is called: 'google-chrome-stable'
:: Running post-transaction hooks...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Refreshing PackageKit...
(3/4) Updating icon theme caches...
(4/4) Updating the desktop file MIME type cache...
sudo ./local-aur build --update-all --install-directly  34.42s user 10.77s system 42% cpu 1:45.33 total
```

**Pull request merged**
